// Voegt extra talen toe aan WEB_STRINGS in public/index.html door een
// merge-blok te injecteren direct na de WEB_STRINGS-definitie. De bestaande
// literal blijft ongemoeid. Placeholders ({n},{name},{side}) en <b> blijven staan.
// Draai: node tools/gen_site_lang.js
const fs = require('fs');
const FILE = 'public/index.html';
let h = fs.readFileSync(FILE, 'utf8');

const EXTRA = {
  it: { pageTitle:'RallyPoint Scoreboard', tagline:'Tabellone dal vivo', pinLabel:'Inserisci il PIN dal tuo orologio', connect:'Connetti', connecting:'Connessione...', pinHint:'Trovi il PIN nell’app RallyPoint sul tuo Garmin.', voiceBtn:'🔊 Voce', voiceBtnOn:'🔊 Voce attiva', voiceBtnTitle:'Leggi il punteggio ad alta voce', voiceSelectTitle:'Scegli una voce', historyBtn:'📋 Storico', historyBtnTitle:'Storico partite', fsEnter:'⛶ Schermo intero', fsExit:'⛶ Esci', fsEnterTitle:'Schermo intero', fsExitTitle:'Esci da schermo intero', livePin:'Live · PIN', tiebreak:'TIE-BREAK', deuce:'PARITÀ', switchSides:'Cambio campo', games:'Giochi', sets:'Set', history:'Storico', historyWithCount:'Storico · {n} punti', histEmpty:'Nessun punto giocato.', winnerSub:'vince la partita', minutes:'minuti', pointsPlayed:'punti giocati', longestRun:'serie più lunga', serve:'Servizio', serves:'al servizio', serveLine:'Servizio: <b>{name}</b> · {side}', sideLeft:'sinistra', sideRight:'destra', serverWaking:'L’orologio si sta attivando... attendi.', noMatchPin:'Nessuna partita per questo PIN.', noServer:'Server non raggiungibile. Riprova.', voiceSet:'Voce selezionata.', voiceOn:'Lettura attiva.', sportPadel:'PADEL', sportTennis:'TENNIS', sportPickleball:'PICKLEBALL', sportTableTennis:'PING-PONG', sportBadminton:'BADMINTON', sportSquash:'SQUASH', teamUs:'Noi', teamThem:'Loro' },
  pl: { pageTitle:'RallyPoint Scoreboard', tagline:'Tablica na żywo', pinLabel:'Wprowadź PIN z zegarka', connect:'Połącz', connecting:'Łączenie...', pinHint:'PIN znajdziesz w aplikacji RallyPoint na zegarku Garmin.', voiceBtn:'🔊 Lektor', voiceBtnOn:'🔊 Lektor wł.', voiceBtnTitle:'Czytaj wynik na głos', voiceSelectTitle:'Wybierz głos', historyBtn:'📋 Historia', historyBtnTitle:'Historia meczów', fsEnter:'⛶ Pełny ekran', fsExit:'⛶ Wyjdź', fsEnterTitle:'Pełny ekran', fsExitTitle:'Wyjdź z pełnego ekranu', livePin:'Na żywo · PIN', tiebreak:'TIE-BREAK', deuce:'RÓWNOWAGA', switchSides:'Zmiana stron', games:'Gemy', sets:'Sety', history:'Historia', historyWithCount:'Historia · {n} pkt', histEmpty:'Brak rozegranych punktów.', winnerSub:'wygrywa mecz', minutes:'minut', pointsPlayed:'rozegranych punktów', longestRun:'najdłuższa seria', serve:'Serwis', serves:'serwuje', serveLine:'Serwis: <b>{name}</b> · {side}', sideLeft:'lewa', sideRight:'prawa', serverWaking:'Zegarek się wybudza... czekaj.', noMatchPin:'Brak meczu dla tego PIN-u.', noServer:'Brak połączenia z serwerem. Spróbuj ponownie.', voiceSet:'Wybrano głos.', voiceOn:'Czytanie włączone.', sportPadel:'PADEL', sportTennis:'TENIS', sportPickleball:'PICKLEBALL', sportTableTennis:'TENIS STOŁOWY', sportBadminton:'BADMINTON', sportSquash:'SQUASH', teamUs:'My', teamThem:'Oni' },
  sv: { pageTitle:'RallyPoint Scoreboard', tagline:'Live-tavla', pinLabel:'Ange PIN från din klocka', connect:'Anslut', connecting:'Ansluter...', pinHint:'Du hittar PIN i RallyPoint-appen på din Garmin.', voiceBtn:'🔊 Röst', voiceBtnOn:'🔊 Röst på', voiceBtnTitle:'Läs upp ställningen', voiceSelectTitle:'Välj en röst', historyBtn:'📋 Historik', historyBtnTitle:'Matchhistorik', fsEnter:'⛶ Helskärm', fsExit:'⛶ Avsluta', fsEnterTitle:'Helskärm', fsExitTitle:'Avsluta helskärm', livePin:'Live · PIN', tiebreak:'TIEBREAK', deuce:'LIKA', switchSides:'Byt sida', games:'Gem', sets:'Set', history:'Historik', historyWithCount:'Historik · {n} poäng', histEmpty:'Inga poäng spelade än.', winnerSub:'vinner matchen', minutes:'minuter', pointsPlayed:'spelade poäng', longestRun:'längsta svit', serve:'Serve', serves:'servar', serveLine:'Serve: <b>{name}</b> · {side}', sideLeft:'vänster', sideRight:'höger', serverWaking:'Klockan väcks... vänta.', noMatchPin:'Ingen match för denna PIN.', noServer:'Når inte servern. Försök igen.', voiceSet:'Röst vald.', voiceOn:'Uppläsning på.', sportPadel:'PADEL', sportTennis:'TENNIS', sportPickleball:'PICKLEBALL', sportTableTennis:'BORDTENNIS', sportBadminton:'BADMINTON', sportSquash:'SQUASH', teamUs:'Vi', teamThem:'De' },
  da: { pageTitle:'RallyPoint Scoreboard', tagline:'Live-tavle', pinLabel:'Indtast PIN fra dit ur', connect:'Forbind', connecting:'Forbinder...', pinHint:'Du finder PIN i RallyPoint-appen på din Garmin.', voiceBtn:'🔊 Stemme', voiceBtnOn:'🔊 Stemme til', voiceBtnTitle:'Læs stillingen højt', voiceSelectTitle:'Vælg en stemme', historyBtn:'📋 Historik', historyBtnTitle:'Kamphistorik', fsEnter:'⛶ Fuldskærm', fsExit:'⛶ Afslut', fsEnterTitle:'Fuldskærm', fsExitTitle:'Afslut fuldskærm', livePin:'Live · PIN', tiebreak:'TIEBREAK', deuce:'LIGE', switchSides:'Skift side', games:'Partier', sets:'Sæt', history:'Historik', historyWithCount:'Historik · {n} point', histEmpty:'Ingen point spillet endnu.', winnerSub:'vinder kampen', minutes:'minutter', pointsPlayed:'spillede point', longestRun:'længste stime', serve:'Serv', serves:'server', serveLine:'Serv: <b>{name}</b> · {side}', sideLeft:'venstre', sideRight:'højre', serverWaking:'Uret vågner... vent.', noMatchPin:'Ingen kamp for denne PIN.', noServer:'Kan ikke nå serveren. Prøv igen.', voiceSet:'Stemme valgt.', voiceOn:'Oplæsning til.', sportPadel:'PADEL', sportTennis:'TENNIS', sportPickleball:'PICKLEBALL', sportTableTennis:'BORDTENNIS', sportBadminton:'BADMINTON', sportSquash:'SQUASH', teamUs:'Os', teamThem:'Dem' },
  no: { pageTitle:'RallyPoint Scoreboard', tagline:'Live-tavle', pinLabel:'Skriv inn PIN fra klokken', connect:'Koble til', connecting:'Kobler til...', pinHint:'Du finner PIN i RallyPoint-appen på din Garmin.', voiceBtn:'🔊 Stemme', voiceBtnOn:'🔊 Stemme på', voiceBtnTitle:'Les stillingen høyt', voiceSelectTitle:'Velg en stemme', historyBtn:'📋 Historikk', historyBtnTitle:'Kamphistorikk', fsEnter:'⛶ Fullskjerm', fsExit:'⛶ Avslutt', fsEnterTitle:'Fullskjerm', fsExitTitle:'Avslutt fullskjerm', livePin:'Live · PIN', tiebreak:'TIEBREAK', deuce:'LIKE', switchSides:'Bytt side', games:'Game', sets:'Sett', history:'Historikk', historyWithCount:'Historikk · {n} poeng', histEmpty:'Ingen poeng spilt ennå.', winnerSub:'vinner kampen', minutes:'minutter', pointsPlayed:'spilte poeng', longestRun:'lengste rekke', serve:'Serve', serves:'server', serveLine:'Serve: <b>{name}</b> · {side}', sideLeft:'venstre', sideRight:'høyre', serverWaking:'Klokken våkner... vent.', noMatchPin:'Ingen kamp for denne PIN-en.', noServer:'Når ikke serveren. Prøv igjen.', voiceSet:'Stemme valgt.', voiceOn:'Opplesing på.', sportPadel:'PADEL', sportTennis:'TENNIS', sportPickleball:'PICKLEBALL', sportTableTennis:'BORDTENNIS', sportBadminton:'BADMINTON', sportSquash:'SQUASH', teamUs:'Oss', teamThem:'Dem' },
  fi: { pageTitle:'RallyPoint Scoreboard', tagline:'Live-taulu', pinLabel:'Syötä kellon PIN-koodi', connect:'Yhdistä', connecting:'Yhdistetään...', pinHint:'Löydät PIN-koodin Garminin RallyPoint-sovelluksesta.', voiceBtn:'🔊 Ääni', voiceBtnOn:'🔊 Ääni päällä', voiceBtnTitle:'Lue tulos ääneen', voiceSelectTitle:'Valitse ääni', historyBtn:'📋 Historia', historyBtnTitle:'Otteluhistoria', fsEnter:'⛶ Koko näyttö', fsExit:'⛶ Poistu', fsEnterTitle:'Koko näyttö', fsExitTitle:'Poistu koko näytöstä', livePin:'Live · PIN', tiebreak:'TIEBREAK', deuce:'TASAN', switchSides:'Vaihda puolta', games:'Pelit', sets:'Erät', history:'Historia', historyWithCount:'Historia · {n} pistettä', histEmpty:'Ei pelattuja pisteitä.', winnerSub:'voittaa ottelun', minutes:'minuuttia', pointsPlayed:'pelattua pistettä', longestRun:'pisin putki', serve:'Syöttö', serves:'syöttää', serveLine:'Syöttö: <b>{name}</b> · {side}', sideLeft:'vasen', sideRight:'oikea', serverWaking:'Kello herää... odota.', noMatchPin:'Ei ottelua tälle PIN-koodille.', noServer:'Palvelimeen ei saada yhteyttä. Yritä uudelleen.', voiceSet:'Ääni valittu.', voiceOn:'Luku päällä.', sportPadel:'PADEL', sportTennis:'TENNIS', sportPickleball:'PICKLEBALL', sportTableTennis:'PÖYTÄTENNIS', sportBadminton:'SULKAPALLO', sportSquash:'SQUASH', teamUs:'Me', teamThem:'He' },
  cs: { pageTitle:'RallyPoint Scoreboard', tagline:'Živá výsledková tabule', pinLabel:'Zadejte PIN z hodinek', connect:'Připojit', connecting:'Připojování...', pinHint:'PIN najdete v aplikaci RallyPoint ve vašich Garmin hodinkách.', voiceBtn:'🔊 Hlas', voiceBtnOn:'🔊 Hlas zap.', voiceBtnTitle:'Číst skóre nahlas', voiceSelectTitle:'Vyberte hlas', historyBtn:'📋 Historie', historyBtnTitle:'Historie zápasů', fsEnter:'⛶ Celá obrazovka', fsExit:'⛶ Zavřít', fsEnterTitle:'Celá obrazovka', fsExitTitle:'Ukončit celou obrazovku', livePin:'Živě · PIN', tiebreak:'TIEBREAK', deuce:'SHODA', switchSides:'Změna stran', games:'Gemy', sets:'Sety', history:'Historie', historyWithCount:'Historie · {n} bodů', histEmpty:'Zatím žádné body.', winnerSub:'vyhrává zápas', minutes:'minut', pointsPlayed:'odehraných bodů', longestRun:'nejdelší série', serve:'Podání', serves:'podává', serveLine:'Podání: <b>{name}</b> · {side}', sideLeft:'vlevo', sideRight:'vpravo', serverWaking:'Hodinky se probúzejí... čekejte.', noMatchPin:'Žádný zápas pro tento PIN.', noServer:'Server je nedostupný. Zkuste znovu.', voiceSet:'Hlas vybrán.', voiceOn:'Čtení zapnuto.', sportPadel:'PADEL', sportTennis:'TENIS', sportPickleball:'PICKLEBALL', sportTableTennis:'STOLNÍ TENIS', sportBadminton:'BADMINTON', sportSquash:'SQUASH', teamUs:'My', teamThem:'Oni' },
  tr: { pageTitle:'RallyPoint Scoreboard', tagline:'Canlı skor tablosu', pinLabel:'Saatinizdeki PIN’i girin', connect:'Bağlan', connecting:'Bağlanıyor...', pinHint:'PIN’i Garmin saatinizdeki RallyPoint uygulamasında bulabilirsiniz.', voiceBtn:'🔊 Ses', voiceBtnOn:'🔊 Ses açık', voiceBtnTitle:'Skoru sesli oku', voiceSelectTitle:'Bir ses seçin', historyBtn:'📋 Geçmiş', historyBtnTitle:'Maç geçmişi', fsEnter:'⛶ Tam ekran', fsExit:'⛶ Çık', fsEnterTitle:'Tam ekran', fsExitTitle:'Tam ekrandan çık', livePin:'Canlı · PIN', tiebreak:'TIE-BREAK', deuce:'BERABERE', switchSides:'Taraf değiştir', games:'Oyunlar', sets:'Setler', history:'Geçmiş', historyWithCount:'Geçmiş · {n} sayı', histEmpty:'Henüz sayı oynanmadı.', winnerSub:'maçı kazanır', minutes:'dakika', pointsPlayed:'oynanan sayı', longestRun:'en uzun seri', serve:'Servis', serves:'servis atar', serveLine:'Servis: <b>{name}</b> · {side}', sideLeft:'sol', sideRight:'sağ', serverWaking:'Saat uyanıyor... bekleyin.', noMatchPin:'Bu PIN için maç yok.', noServer:'Sunucuya ulaşılamıyor. Tekrar deneyin.', voiceSet:'Ses seçildi.', voiceOn:'Okuma açık.', sportPadel:'PADEL', sportTennis:'TENİS', sportPickleball:'PICKLEBALL', sportTableTennis:'MASA TENİSİ', sportBadminton:'BADMİNTON', sportSquash:'SKUAŞ', teamUs:'Biz', teamThem:'Onlar' },
  ro: { pageTitle:'RallyPoint Scoreboard', tagline:'Tabelă live', pinLabel:'Introdu PIN-ul de pe ceas', connect:'Conectează', connecting:'Se conectează...', pinHint:'Găseşti PIN-ul în aplicația RallyPoint de pe Garmin.', voiceBtn:'🔊 Voce', voiceBtnOn:'🔊 Voce activă', voiceBtnTitle:'Citeşte scorul cu voce tare', voiceSelectTitle:'Alege o voce', historyBtn:'📋 Istoric', historyBtnTitle:'Istoric meciuri', fsEnter:'⛶ Ecran complet', fsExit:'⛶ Ieşire', fsEnterTitle:'Ecran complet', fsExitTitle:'Ieşi din ecran complet', livePin:'Live · PIN', tiebreak:'TIE-BREAK', deuce:'EGALITATE', switchSides:'Schimbă terenul', games:'Game-uri', sets:'Seturi', history:'Istoric', historyWithCount:'Istoric · {n} puncte', histEmpty:'Niciun punct jucat încă.', winnerSub:'câştigă meciul', minutes:'minute', pointsPlayed:'puncte jucate', longestRun:'cea mai lungă serie', serve:'Serviciu', serves:'serveşte', serveLine:'Serviciu: <b>{name}</b> · {side}', sideLeft:'stânga', sideRight:'dreapta', serverWaking:'Ceasul se trezeşte... aşteaptă.', noMatchPin:'Niciun meci pentru acest PIN.', noServer:'Serverul nu răspunde. Încearcă din nou.', voiceSet:'Voce selectată.', voiceOn:'Citire activă.', sportPadel:'PADEL', sportTennis:'TENIS', sportPickleball:'PICKLEBALL', sportTableTennis:'TENIS DE MASĂ', sportBadminton:'BADMINTON', sportSquash:'SQUASH', teamUs:'Noi', teamThem:'Ei' },
  hu: { pageTitle:'RallyPoint Scoreboard', tagline:'Élő eredménytábla', pinLabel:'Add meg az órád PIN-kódját', connect:'Csatlakozás', connecting:'Csatlakozás...', pinHint:'A PIN-kódot a Garmin órád RallyPoint appjában találod.', voiceBtn:'🔊 Hang', voiceBtnOn:'🔊 Hang be', voiceBtnTitle:'Eredmény felolvasása', voiceSelectTitle:'Válassz hangot', historyBtn:'📋 Előzmények', historyBtnTitle:'Meccs előzmények', fsEnter:'⛶ Teljes képernyő', fsExit:'⛶ Kilépés', fsEnterTitle:'Teljes képernyő', fsExitTitle:'Kilépés a teljes képernyőből', livePin:'Élő · PIN', tiebreak:'TIE-BREAK', deuce:'EGYENLŐ', switchSides:'Oldalcsere', games:'Gémek', sets:'Szettek', history:'Előzmények', historyWithCount:'Előzmények · {n} pont', histEmpty:'Még nincs játszott pont.', winnerSub:'megnyeri a meccset', minutes:'perc', pointsPlayed:'játszott pont', longestRun:'leghosszabb sorozat', serve:'Adógás', serves:'adogat', serveLine:'Adógás: <b>{name}</b> · {side}', sideLeft:'bal', sideRight:'jobb', serverWaking:'Az óra ébred... várj.', noMatchPin:'Nincs meccs ehhez a PIN-hez.', noServer:'A szerver nem elérhető. Próbáld újra.', voiceSet:'Hang kiválasztva.', voiceOn:'Felolvasás be.', sportPadel:'PADEL', sportTennis:'TENISZ', sportPickleball:'PICKLEBALL', sportTableTennis:'ASZTALITENISZ', sportBadminton:'TOLLASLABDA', sportSquash:'FALLABDA', teamUs:'Mi', teamThem:'Ők' },
};

// Gesproken zinnen (TTS via ElevenLabs multilingual). Placeholders behouden.
const SPOKEN = {
  it: { spokenAdv:'Vantaggio {name}.', spokenAdvServer:'Vantaggio interno.', spokenAdvReceiver:'Vantaggio esterno.', spokenDeuce:'Parità.', spokenEqual:'{n} pari.', spokenSetWon:'Set vinto. Set {a} a {b}.', spokenGameWon:'Gioco. Giochi {a} a {b}.', spokenServe:'Al servizio {name}.', spokenMatchWon:'{name} vince la partita, {a} a {b} nei set.' },
  pl: { spokenAdv:'Przewaga {name}.', spokenAdvServer:'Przewaga serwujący.', spokenAdvReceiver:'Przewaga odbierający.', spokenDeuce:'Równowaga.', spokenEqual:'Po {n}.', spokenSetWon:'Set wygrany. Sety {a} do {b}.', spokenGameWon:'Gem. Gemy {a} do {b}.', spokenServe:'Serwuje {name}.', spokenMatchWon:'{name} wygrywa mecz, {a} do {b} w setach.' },
  sv: { spokenAdv:'Fördel {name}.', spokenAdvServer:'Fördel inne.', spokenAdvReceiver:'Fördel ute.', spokenDeuce:'Lika.', spokenEqual:'{n} lika.', spokenSetWon:'Set vunnet. Set {a} till {b}.', spokenGameWon:'Game. Gem {a} till {b}.', spokenServe:'{name} servar.', spokenMatchWon:'{name} vinner matchen, {a} till {b} i set.' },
  da: { spokenAdv:'Fordel {name}.', spokenAdvServer:'Fordel inde.', spokenAdvReceiver:'Fordel ude.', spokenDeuce:'Lige.', spokenEqual:'{n} lige.', spokenSetWon:'Sæt vundet. Sæt {a} til {b}.', spokenGameWon:'Parti. Partier {a} til {b}.', spokenServe:'{name} server.', spokenMatchWon:'{name} vinder kampen, {a} til {b} i sæt.' },
  no: { spokenAdv:'Fordel {name}.', spokenAdvServer:'Fordel inne.', spokenAdvReceiver:'Fordel ute.', spokenDeuce:'Like.', spokenEqual:'{n} like.', spokenSetWon:'Sett vunnet. Sett {a} til {b}.', spokenGameWon:'Game. Game {a} til {b}.', spokenServe:'{name} server.', spokenMatchWon:'{name} vinner kampen, {a} til {b} i sett.' },
  fi: { spokenAdv:'Etu {name}.', spokenAdvServer:'Etu syöttäjä.', spokenAdvReceiver:'Etu vastaanottaja.', spokenDeuce:'Tasan.', spokenEqual:'{n} tasan.', spokenSetWon:'Erä voitettu. Erät {a}–{b}.', spokenGameWon:'Peli. Pelit {a}–{b}.', spokenServe:'{name} syöttää.', spokenMatchWon:'{name} voittaa ottelun, erät {a}–{b}.' },
  cs: { spokenAdv:'Výhoda {name}.', spokenAdvServer:'Výhoda podávající.', spokenAdvReceiver:'Výhoda přijímající.', spokenDeuce:'Shoda.', spokenEqual:'Shodně {n}.', spokenSetWon:'Set získán. Sety {a} ku {b}.', spokenGameWon:'Hra. Hry {a} ku {b}.', spokenServe:'Podává {name}.', spokenMatchWon:'{name} vyhrává zápas, {a} ku {b} na sety.' },
  tr: { spokenAdv:'Avantaj {name}.', spokenAdvServer:'Avantaj servis.', spokenAdvReceiver:'Avantaj karşılayan.', spokenDeuce:'Berabere.', spokenEqual:'{n} eşit.', spokenSetWon:'Set alındı. Setler {a} - {b}.', spokenGameWon:'Oyun. Oyunlar {a} - {b}.', spokenServe:'Servis {name}.', spokenMatchWon:'{name} maçı kazandı, setlerde {a} - {b}.' },
  ro: { spokenAdv:'Avantaj {name}.', spokenAdvServer:'Avantaj la serviciu.', spokenAdvReceiver:'Avantaj la primire.', spokenDeuce:'Egalitate.', spokenEqual:'{n} egal.', spokenSetWon:'Set câştigat. Seturi {a} la {b}.', spokenGameWon:'Ghem. Ghemuri {a} la {b}.', spokenServe:'La serviciu {name}.', spokenMatchWon:'{name} câştigă meciul, {a} la {b} la seturi.' },
  hu: { spokenAdv:'Előny {name}.', spokenAdvServer:'Előny adogató.', spokenAdvReceiver:'Előny fogadó.', spokenDeuce:'Egyenlő.', spokenEqual:'{n} egyenlő.', spokenSetWon:'Szett megnyerve. Szettek {a}–{b}.', spokenGameWon:'Game. Gémek {a}–{b}.', spokenServe:'{name} adogat.', spokenMatchWon:'{name} megnyeri a meccset, {a}–{b} szettben.' },
};
// gesproken sleutels samenvoegen in EXTRA
for (const lg of Object.keys(SPOKEN)) { Object.assign(EXTRA[lg], SPOKEN[lg]); }

// merge-blok bouwen
const MARK_A = '// --- Extra talen (auto-gegenereerd, tools/gen_site_lang.js) ---';
const MARK_B = '// --- einde extra talen ---';
let merge = '\n' + MARK_A + '\n';
merge += 'const WEB_STRINGS_EXTRA = ' + JSON.stringify(EXTRA) + ';\n';
merge += 'for (var _lg in WEB_STRINGS_EXTRA) { var _d = WEB_STRINGS_EXTRA[_lg]; for (var _k in _d) { if (WEB_STRINGS[_k]) { WEB_STRINGS[_k][_lg] = _d[_k]; } } }\n';
merge += MARK_B + '\n';

// bestaand blok verwijderen (idempotent)
const ai = h.indexOf(MARK_A);
if (ai >= 0) {
  const bi = h.indexOf(MARK_B, ai);
  if (bi >= 0) { h = h.slice(0, ai).replace(/\n$/, '') + h.slice(bi + MARK_B.length); }
}

// injecteer na de WEB_STRINGS-definitie (eerste "\n};" na "const WEB_STRINGS = {")
const anchor = 'const WEB_STRINGS = {';
const startI = h.indexOf(anchor);
if (startI < 0) { console.error('WEB_STRINGS niet gevonden'); process.exit(1); }
const closeI = h.indexOf('\n};', startI);
if (closeI < 0) { console.error('einde WEB_STRINGS niet gevonden'); process.exit(1); }
const insertAt = closeI + 3; // na "\n};"
h = h.slice(0, insertAt) + merge + h.slice(insertAt);
fs.writeFileSync(FILE, h);
console.log('geïnjecteerd:', Object.keys(EXTRA).length, 'talen,', Object.keys(EXTRA.it).length, 'keys elk (incl. gesproken)');
